--1
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE (TO_NUMBER(TO_CHAR(HIRE_DATE,'MM'))= 4 AND TO_NUMBER(TO_CHAR(HIRE_DATE,'D'))=3)
    OR (TO_NUMBER(TO_CHAR(HIRE_DATE,'MM'))= 5 AND TO_NUMBER(TO_CHAR(HIRE_DATE,'D'))=4);
    
--2
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES RIGHT OUTER JOIN DEPARTMENTS ON(EMPLOYEES.EMPLOYEE_ID=DEPARTMENTS.MANAGER_ID);

--3
SELECT COUNTRY_NAME
FROM DEPARTMENTS JOIN LOCATIONS USING(LOCATION_ID) JOIN COUNTRIES USING(COUNTRY_ID)
WHERE UPPER(DEPARTMENT_NAME)='PUBLIC RELATIONS';

--4
SELECT *
FROM EMPLOYEES LEFT OUTER JOIN DEPARTMENTS USING(DEPARTMENT_ID) JOIN LOCATIONS USING(LOCATION_ID) JOIN COUNTRIES USING(COUNTRY_ID) JOIN REGIONS USING(REGION_ID)
WHERE UPPER(REGION_NAME)='AMERICAS';

--5
SELECT *
FROM EMPLOYEES LEFT OUTER JOIN DEPARTMENTS USING(DEPARTMENT_ID) JOIN LOCATIONS USING(LOCATION_ID) JOIN COUNTRIES USING(COUNTRY_ID) JOIN REGIONS USING(REGION_ID)
WHERE  TO_NUMBER(TO_CHAR(HIRE_DATE,'MM')) IN (5,6,7)
    AND UPPER(REGION_NAME)='ASIA';
