--1. Seleccionar el salario máximo de cada departamento, mostrando el nombre del departamento y dicha cantidad.

SELECT DEPARTMENT_NAME, MAX(SALARY)
FROM DEPARTMENTS JOIN EMPLOYEES USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

SELECT DEPARTMENT_NAME, MAX(NVL(SALARY,0))
FROM DEPARTMENTS LEFT OUTER JOIN EMPLOYEES USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME;

--2. Seleccionar el salario mínimo de cada departamento, para aquellos departamentos cuyo salario minimo sea menor que 5000$.

SELECT DEPARTMENT_NAME, MIN(SALARY)
FROM DEPARTMENTS JOIN EMPLOYEES USING(DEPARTMENT_ID)
GROUP BY DEPARTMENT_NAME
HAVING MIN(SALARY) < 5000;

--3. Seleccionar el número de empleados que trabajan en cada oficina, mostrando el STREET_ADDRESS y dicho numero; hay que ordenar la salida de mayor a menor.

SELECT STREET_ADDRESS,LOCATION_ID
FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID) JOIN LOCATIONS USING(LOCATION_ID)
GROUP BY STREET_ADDRESS, LOCATION_ID
ORDER BY LOCATION_ID DESC;

--CORREGIDO
SELECT STREET_ADDRESS,COUNT(*)
FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID) JOIN LOCATIONS USING(LOCATION_ID)
GROUP BY STREET_ADDRESS
ORDER BY COUNT(*) DESC;

--4. Modificar la consulta anterior para que muestre las localizaciones que no tienen ningún empleado.

SELECT LOCATION_ID
FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID) RIGHT OUTER JOIN LOCATIONS USING(LOCATION_ID)
WHERE EMPLOYEE_ID IS NULL
GROUP BY LOCATION_ID
ORDER BY LOCATION_ID ;

--CORREGIDO
SELECT STREET_ADDRESS,COUNT(EMPLOYEE_ID)
FROM EMPLOYEES RIGHT OUTER JOIN DEPARTMENTS USING(DEPARTMENT_ID) RIGHT OUTER JOIN LOCATIONS USING(LOCATION_ID)
GROUP BY STREET_ADDRESS
ORDER BY COUNT(EMPLOYEE_ID) DESC;

--5. Sea el salario que es cobrado por más personas a la vez. Mostrar dicho número de personas.

SELECT MAX(COUNT(*))
FROM EMPLOYEES
GROUP BY SALARY;
--COMO HACER PARA QUE SE VEA TAMBIEN EL SALARIO

--6. Seleccionar el numero de empleados que empezaron a trabajar cada año, ordenando la salida por el año.

SELECT EXTRACT(YEAR FROM HIRE_DATE),COUNT(*)
FROM EMPLOYEES
GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
ORDER BY EXTRACT(YEAR FROM HIRE_DATE);